### ISSUE TITLE
Improve locks

### ISSUE THREAD

**Issue by Amjad50** [Amjad50/OS#3]
Use a better locking, like test loop, that only uses `load` and only try `compare_exchange` once it can actually do it. Reduce contention.

Also other improvements

### Tasks
- [ ] reduce contention in locking
- [ ] Keep track of time holding the lock
- [ ] Keep track of time needed to wait for the lock
- [ ] Assert several metrics (go back to reddit for the suggestions ppl mentioned)
- [ ] (Need to check if its good) Keep track of owner CPU in the `Lock` itself and use `Usize` and not `Bool`
- [ ] Add more functionalities and structs around locks
    - [ ] Rwlock

**Comment by Amjad50** [comment]
This was part of the `Video Player` milestone: https://github.com/Amjad50/Emerald/milestone/2

But decided to skip implementing time tracking for now, since it will make the lock more complicated than needed right now.

This will be moved outside of the milestone, but the goal needed is already implemented in #58
